### ISSUE TITLE
db file is encrytped

### ISSUE THREAD

**Issue by boonhapus** [mdiller/dotabase#1]
With 7.06f, the db file is now encrypted - was this intentional?

Thanks,
\- SN

**Comment by mdiller** [comment]
Hmm that's strange. The dotabase.db file is encrypted and you can't open it?
(sorry that I didn't see this until now)

**Comment by boonhapus** [comment]
That's correct. I get an encrypted message when trying to open via a DB browser. I haven't tried via python, but figured I would get the same result.

![image](https://user-images.githubusercontent.com/14192437/30757586-d959380e-9f94-11e7-8feb-4aa5cca510ec.png)

**Comment by mdiller** [comment]
Hmm that's strange. Can you try running the example python script from the readme?

Also have you tried not entering a password and just clicking "OK"?

**Comment by boonhapus** [comment]
Sure, once I get home. The "OK" won't work without a password. For what it's worth, it worked fine before https://github.com/mdiller/dotabase/commit/75d6c379bb01a8fb2628f27db17459192047af68

**Comment by boonhapus** [comment]
@mdiller Interesting, it appears as if I attempt to download just the db from this repo, it says it is encrypted.. but if I grab the entire repo, it works just fine. How odd. I don't have much of a need for anything but the db, so I eventually plan to look over your builder!

**Comment by mdiller** [comment]
Huh that's interesting. I wonder why.
