### ISSUE TITLE
how to extract the data from the new vpk files?

### ISSUE THREAD

**Issue by MansourM** [mdiller/dotabase#4]
I wanted to build some stuff using your database, but I noticed that i needed the resources (images, etc) so i searched a bit and found out that i need GCFScape to extract vpk files from dota2, but it seems this software is unable to extract data from the new format, i don't have a single vpk file, I have pak01_000.vpk, pak01_001.vpk, pak01_002.vpk, etc, how can i get the data from these files? :)
thanks in advance

**Comment by mdiller** [comment]
Oops didn't see this notification till now. I'm using the Decompiler from [ValveResourceFormat](https://github.com/SteamDatabase/ValveResourceFormat). It's a little tricky to get familiar with but these are the command line parameters I'm using:
```
dotnet Decompiler.dll -i "$dota_vpk" --recursive --vpk_cache -d -e "txt,dat,vsndevts_c,vxml_c,vjs_c,vcss_c,png,cfg,res,vsnd_c,vtex_c" -o "F:\dota_vpk" --threads 16
```
I'm also hosting some of the files at http://dotabase.dillerm.io/dota-vpk/
ex: http://dotabase.dillerm.io/dota-vpk/panorama/images/heroes/npc_dota_hero_death_prophet_png.png

**Comment by MansourM** [comment]
thanks for your response, it worked out like a charm!

ill just add a few things before this issue is closed for the future generations ;D
1. you need to have version 2.x of [dotnet core](https://dotnet.microsoft.com/download/dotnet-core) installed
2. target "pak01_dir.vpk" when you are running the command
3. your pc can probably take way more than 16 threads if you want to do it fast but with 16 you can just run it in the background while you use your pc

the command that I ended up using

> dotnet "E:\vpk\decompiler\Decompiler.dll" -i "E:\vpk\bundles\pak01_dir.vpk" --recursive --vpk_cache -d -e "txt,dat,vsndevts_c,vxml_c,vjs_c,vcss_c,png,cfg,res,vsnd_c,vtex_c" -o "E:\vpk\extracted" --threads 16

btw just-in-case I moved the files, does that matter? I mean is there any chance that the process can damage the vpk files? (i wonder if the absolute path of the files is stored in pak_dir and moving does not matter anyway, but too lazy to check ;)

**Comment by mdiller** [comment]
Glad it worked!

As far as I understand it shouldn't matter. I think they reference the other vpk files in the dota directory though so you might have to move them all together.

No, the process shouldnt modify the vpk files in any way, its just reading.
